-- SQLBook: Code
-- Active: 1663797586807@@127.0.0.1@3306@ma_nouvelle_base
USE Ma_nouvelle_base;

DROP TABLE IF EXISTS EMP;

DROP TABLE IF EXISTS DEPT ;

CREATE TABLE DEPT(
    NUMDEPT INT ,
    NOMD VARCHAR(30) ,
    LIEU VARCHAR(30)
    -- CONSTRAINT PK_DEPT PRIMARY KEY(NUMDEPT) 
);

CREATE TABLE EMP(
    NUMEMP INT ,
    NOM VARCHAR(30),
    FONCTION VARCHAR(30),
    NUMSUP INT, 
    DATEEMBAUCHE DATE, 
    SAL INT ,
    COMM INT ,
    NUMDEPT INT 
   --  CONSTRAINT PK_EMP PRIMARY KEY(NUMEMP)

);

INSERT INTO DEPT VALUES(10, 'DIRECTION', 'NEW YORK');

DESCRIBE DEPT;

DESCRIBE EMP;

INSERT INTO DEPT VALUES(10, 'DIRECTION', 'NEW YORK');

SELECT * FROM DEPT;

INSERT INTO EMP VALUES(7782, 'CLARCK','MANAGER' ,7839, '1981-06-8', 2450, NULL, 10);
INSERT INTO EMP VALUES(7782, 'CLARCK','MANAGER' ,7839, '1981-06-8', 2450, NULL, 20);

DROP TABLE EMP;
DROP TABLE DEPT;

CREATE TABLE DEPT(
    NUMDEPT INT ,
    NOMD VARCHAR(30) ,
    LIEU VARCHAR(30),
    CONSTRAINT PK_DEPT PRIMARY KEY(NUMDEPT)
);

CREATE TABLE EMP(
    NUMEMP INT ,
    NOM VARCHAR(30),
    FONCTION VARCHAR(30),
    NUMSUP INT, 
    DATEEMBAUCHE DATE, 
    SAL INT ,
    COMM INT ,
    NUMDEPT INT ,
    CONSTRAINT PK_EMP PRIMARY KEY(NUMEMP),
    CONSTRAINT FK_EMP FOREIGN KEY(NUMDEPT) REFERENCES DEPT(NUMDEPT)
);

ALTER TABLE DEPT ADD CONSTRAINT UNIQUE(LIEU);
INSERT INTO DEPT VALUES(30, 'PROF', 'NEW YORK');

ALTER TABLE EMP ADD CONSTRAINT CHECK(SAL > 500) ;
INSERT INTO EMP VALUES(7780, 'CLARCK','MANAGER' ,7839, '1981-06-8', 450, NULL, 10); 

INSERT INTO DEPT VALUES(10, 'DIRECTION', 'NEW_YORK');
INSERT INTO DEPT VALUES(10, 'DIRECTION', 'NEW_YORK');

INSERT INTO DEPT VALUES(40, 'VENTE', 'CHICAGO');
INSERT INTO EMP VALUES(7839, 'KING','PRESIDENT' , NULL, '1982-11-18', 5000, NULL, 10); 

INSERT INTO EMP VALUES(7839, 'KING','PRESIDENT' , NULL, '1982-11-18', 5000, NULL, 10); 
-- cette employé existe déjà par son identifiant --

INSERT INTO EMP VALUES(7782, 'CLARCK','MANAGER' ,7839, '1981-06-8', 5000, NULL, 10);

SELECT * FROM EMP;

INSERT INTO EMP VALUES(7566, 'JONES','MANAGER' ,7839, '1982-03-18', 2975, NULL, 10, NULL);

ALTER TABLE EMP ADD EMAIL_ADRESS VARCHAR(45);
ALTER TABLE EMP ADD CONSTRAINT CHECK(EMAIL_ADRESS LIKE '%@%'); 

DESCRIBE EMP;
DESCRIBE DEPT;

--  delete an record from the table EMP
DELETE FROM  EMP WHERE NUMEMP = 7646;

INSERT INTO EMP VALUES(7646, 'OLIVER','MANAGER' ,7839, '1982-03-18', 2975, NULL, 10, 'oliviertina29@gmail.com');

SELECT * FROM DEPT;
SELECT * FROM EMP;

DELETE FROM DEPT WHERE NUMDEPT = 30;
DELETE FROM DEPT WHERE NUMDEPT = 10;
-- Si l'enregistrement est liée on doit effectuer la suppression d'abord dans la table ou le champ est re de liaison clée etrangere --
DELETE FROM EMP WHERE NUMDEPT = 10;
DELETE FROM DEPT WHERE NUMDEPT = 10;
SELECT * FROM DEPT;

ALTER TABLE DEPT DROP PRIMARY KEY;

INSERT INTO DEPT VALUES(70, 'VENTE', 'BOSTON');

ALTER TABLE DEPT ADD CONSTRAINT UNIQUE(NOMD);

-- SQLBook: Code


-- 28 Septembre 2022 --
SELECT * FROM EMP;
SELECT * FROM DEPT;